title: "My Documentation Site"
description: "Documentation for my project"
baseurl: "" # Set to your repository name if it's not your GitHub user site
url: "https://bh-siva-git.github.io" # Update to your GitHub Pages URL
